# Generated by Django 3.2.5 on 2021-07-21 20:25

from django.db import migrations, models
from datetime import datetime

now = datetime.now()

current_time = now.strftime("%H:%M:%S")

class Migration(migrations.Migration):

    dependencies = [
        ('Routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='date',
        ),
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='time',
            field=models.TimeField(default=current_time),
            preserve_default=False,
        ),
    ]
